### ISSUE TITLE
write letter to editor and suggest referees

### ISSUE THREAD

**Issue by jovo** [jhu-graphstat/LLG#11]

**Comment by TangRunze** [comment]
Here are the suggestions Jovo gave:
- [ ] In the first paragraph, we need to specify what kind of article we are submitting ("research article" in this case?)
- [ ] The second paragraph should focus on the motivation. It might be better that the paragraph starts with "As neuroscientists, ..." to make it clear that people care about estimating the mean given multiple graphs.
- [ ] The third paragraph should focus on the implications, e.g. especially for a small number of samples.

**Comment by dpmcsuss** [comment]
@jovo Feel free to make any other changes.
