### ISSUE TITLE
Remaining Issues from Jovo #1

### ISSUE THREAD

**Issue by dpmcsuss** [jhu-graphstat/LLG#5]
These are the things that I have not yet fixed
- [x] 1. "Also, the ARE does not 204 depend on the number of graphs M, so the larger the graphs are, the better Pˆ is 205 relative to A ̄, regardless of M. " this was a surpising result, right? not in retrospect perhaps, but we didn't realize that would be true?! we should highlight that! in general, we should be more clear about our contributions, we defined a new estimator, we proved RE results, in particular, that do not depend on M!
- [x] 2. "While there is no compact analytical formula for the relative 214 efficiency of Pˆ versus A ̄ in the general RDPG case, using the same ideas as in 215 Theorem 3.2, we can show that RE(A ̄ij , Pˆij ) = O(1/N )." is that a lemma? a conjecture? a theorem? clarify
- [x] 3. Fig 5 should have a scalebar
- [x] 4. "Rank-based methods and robust likelihood methods could be very useful in that case. " provide a citation.
- [x] 5. intuitively, as N increases, with fixed K and rho and M, shouldn't Phat do much better than Abar? shouldn't we discuss this case in the discussion?

**Comment by dpmcsuss** [comment]
Re point 2 above. We could write it as a Lemma but I was hoping to leave it somewhat informal. If we put it as a Lemma I think I would just say that the proof follows closely to that of the other results.

**Comment by dpmcsuss** [comment]
@jovo For 5, did you just want a bit of prose about the theory in the discussion or something else?

**Comment by dpmcsuss** [comment]
For 1, I'm thinking of adding a paragraph with more of summary of our results in the intro that highlights our contributions. I'll read through it at some point too with 1 in mind.

**Comment by jovo** [comment]
- re 2: i think a lemma without proof is great
- re 5: prose in the discussion is great.

**Comment by dpmcsuss** [comment]
Definitely improved :-)
