### ISSUE TITLE
Issues for current draft (Part I)

### ISSUE THREAD

**Issue by TangRunze** [jhu-graphstat/LLG#8]
- [x] Move parenthesis after Daniel to Carey in the author
- [x] Line 16: todays standards -> today's standards
- [x] Line 21: this doesn't other -> this doesn't mean that other?
- [x] Line 105: LPM is different from LPG in Line 99
- [x] Line 120: Aij iid Bern, i, j seems to be the variable so is it identically distributed?
- [x] Line 121: outter -> outer
- [x] Line 133: n -> N
- [x] Fig 1: Parenthesis after see Section 3.1; between O and 1 -> between 0 and 1
- [x] Algorithm 1: 1. s1 > s2 > ... > sd; 3. R^{N \times d}; We are assuming distinct eigenvalues here?
- [x] Algorimth 2: 2. n -> N; 5. \tilde{P} -> \tilde{P}^{(0)}; We don't need an extra step here?
- [x] Line 215: Section 2 -> Section 3
- [x] Line 220: \tau are drawn from \rho. But Line 135 seems to be opposite?
- [x] Fig 2: block 1 -> block one; \rho_1 = is close to 1 -> \rho_1 is close to 1

**Comment by dpmcsuss** [comment]
I'll work out the \tau drawn from \rho thing. See #9
